### ISSUE TITLE
Error: EACCES: permission denied, open '/var/task/api/index.ts'

### ISSUE THREAD

**Issue by i8ramin** [vercel/og-image#139]
- Cloned repo
- Modified `vercel.json` config:
```
{
  "rewrites": [{ "source": "/(.+)", "destination": "/api" }]
}
```
- Deployed to **vercel** using `now`

When I visit the site (https://og-image-cpsxj0in2.vercel.app/), I get the following error:

```
[GET] /**Hello**%20World.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fvercel-triangle-black.svg
10:04:15:44
2020-10-23T14:04:15.630Z	undefined	ERROR	Error: EACCES: permission denied, open '/var/task/api/index.ts'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /var/task/___now_launcher.js:26:28
    at Object.<anonymous> (/var/task/___now_launcher.js:74:7)
    at Module._compile (internal/modules/cjs/loader.js:1137:30) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/var/task/api/index.ts'
}
RequestId: 7ec58ba6-b77f-46db-9422-47788402a5c0 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Seems to work fine locally. Any help would be greatly appreciate

**Comment by styfle** [comment]
Did you modify any code? This project deploys just fine so I can't reproduce.

You can see the last deployment was 3 days ago 
![image](https://user-images.githubusercontent.com/229881/113951253-39515780-97e1-11eb-9810-91bbebc6d10e.png)

Are you still having this issue?
