### ISSUE TITLE
WSL2 Failed to complete request socket hang up

### ISSUE THREAD

**Issue by khromov** [vercel/og-image#152]
I've set the service up according to the instructions, but the image generation requests just hang with the following error in the log:

```
HTTP /**Hello**%20World.png
Error! Failed to complete request to /**Hello**%20World.png: Error: socket hang up
Error: Protocol error (Target.setAutoAttach): Target closed.
    at /home/k/GitHub/og-image/node_modules/puppeteer-core/src/common/Connection.ts:270:57
    at new Promise (<anonymous>)
    at CDPSession.send (/home/k/GitHub/og-image/node_modules/puppeteer-core/src/common/Connection.ts:269:12)
    at Page._initialize (/home/k/GitHub/og-image/node_modules/puppeteer-core/src/common/Page.ts:487:20)
    at Function.create (/home/k/GitHub/og-image/node_modules/puppeteer-core/src/common/Page.ts:361:16)
    at /home/k/GitHub/og-image/node_modules/puppeteer-core/src/common/Target.ts:120:14
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Browser._createPageInContext (/home/k/GitHub/og-image/node_modules/puppeteer-core/src/common/Browser.ts:374:18)
    at getPage (/home/k/GitHub/og-image/api/_lib/chromium.ts:12:13)
    at Object.getScreenshot (/home/k/GitHub/og-image/api/_lib/chromium.ts:17:18)
```

Using Windows 10 / WSL2.

**Comment by khromov** [comment]
The same project works on a Mac, so this might potentially be a Linux or (more likely) a WSL2 issue.

**Comment by styfle** [comment]
Take a look at the expected path here: https://github.com/vercel/og-image/blob/f7a80f833d65a087b0128b6034ca8caf027798bc/api/_lib/options.ts#L2

**Comment by khromov** [comment]
@styfle When using WSL2 it will use the linux Chrome binary. This issue seems related to: https://github.com/puppeteer/puppeteer/issues/1837

I tried the workarounds in the thread about and also to replace `puppeteer-core` with regular `puppeteer`, but unfortunately no luck. The issue is that the `.screenshot()` promise never resolves:
https://github.com/vercel/og-image/blob/7d879675da4161c3198261fe1944e667087104b5/api/_lib/chromium.ts#L20

Based on the Chromium log (Which can be seen by running with the debug flag: `DEBUG="puppeteer:*" vercel dev`) it looks like Chromium takes the screenshot but then hangs infinitely.

**Comment by styfle** [comment]
> When using WSL2 it will use the linux Chrome binary

You can configure the binary used by modifying these lines. 

https://github.com/vercel/og-image/blob/f7a80f833d65a087b0128b6034ca8caf027798bc/api/_lib/options.ts#L2-L6

If that doesn't work, then it likely is the upstream issue with puppeteer.
